security:
  oauth2:
    resource:
      # token-info-uri: http://localhost:9191/oauth/check_token
      token-info-uri: http://103.129.200.58:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
server:
  port: 8181
  servlet:
    context-path: /api/v1/intService

#server:
#  servlet:
#    session:
#      cookie:
#        name: KSESSION
#    context-path: /api/v1/intService
#  port: 8181



  #resources: # Static resources
  #  static-locations: file:src/main/resources/static/
  #  cache:
  #    period: 0


#103.129.200.58
