#103.129.200.58
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      auto-approve-scopes: '.*'
      user-authorization-uri: http://103.129.200.58:9191/oauth/authorize
      access-token-uri: http://103.129.200.58:9191/oauth/token
      #clientAuthenticationScheme: form
    resource:
      token-info-uri: http://103.129.200.58:9191/oauth/check_token
server:
  servlet:
    session:
      cookie:
        name: KSESSION
  port: 8080

spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/,file:src/main/resources/templates/
      cache:
        period: 0
  #resources: # Static resources
  #  static-locations: file:src/main/resources/static/
  #  cache:
  #    period: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#103.129.200.58
feign:
  httpclient:
    connection-timeout: 160000000
    disable-ssl-validation: false
